package co.weeby.event;

public enum MessageEventType {
	UNKOWN_TYPE,
	CLIENT_CONNECT_EVT,
	USER_DATA_AVAI_EVT,
	CLIENT_SEND_MESSAGE_EVT,
	SERVER_NODE_DATA_AVAI_EVT,
	USER_ROOM_EVT,
	FALLBACK_EVT,
	INTERNAL_USER_STATE_EVT,
	INTERNAL_USER_ROOM_EVT,
	INTERNAL_USER_SEND_MSG_EVT,

}
